apiVersion: v1
kind: Namespace
metadata:
  name: kepler
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kepler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kepler
    spec:
      hostNetwork: true
      serviceAccountName: kepler
      containers:
      - name: kepler
        image: quay.io/sustainable_computing_io/kepler:v0.11.3
        imagePullPolicy: IfNotPresent
        command: ["/usr/bin/kepler"]
        args:
        - "--v=2"
        securityContext:
          privileged: true
        env:
        - name: ENABLE_RAPL
          value: "false"
        - name: EXPOSE_HARDWARE_COUNTER_METRICS
          value: "false"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
        - name: tracing
          mountPath: /sys/kernel/debug/tracing
          readOnly: true
      volumes:
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: tracing
        hostPath:
          path: /sys/kernel/debug/tracing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kepler
  namespace: kepler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kepler
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kepler
subjects:
- kind: ServiceAccount
  name: kepler
  namespace: kepler
roleRef:
  kind: ClusterRole
  name: kepler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kepler
  namespace: kepler
  labels:
    app.kubernetes.io/name: kepler
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: kepler
  ports:
  - name: http
    port: 9102
    targetPort: 9102
