apiVersion: batch/v1
kind: Job
metadata:
  name: fashion-mnist-pipeline
  labels:
    project: green-mlops-thesis
spec:
  template:
    metadata:
      labels:
        project: green-mlops-thesis
    spec:
      restartPolicy: Never
      
      # Define the Shared Storage
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: fashion-mnist-pvc
      
      # 1. INIT CONTAINER: ETL (Runs First)
      initContainers:
      - name: etl-step
        image: green-mlops-fashion:v1
        imagePullPolicy: Never
        command: ["python", "src/etl.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        - name: shared-data
          mountPath: /app/metrics

      # 2. MAIN CONTAINER: TRAIN (Runs Second)
      containers:
      - name: train-step
        image: green-mlops-fashion:v1
        imagePullPolicy: Never
        command: ["python", "src/train.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /app/data
        - name: shared-data
          mountPath: /app/metrics